var tileDefs = {
    0:  {'name': 'AIR'},
    1:  {'name': 'SOLID STANDARD'},
    2:  {'name': 'SOLID BUMPABLE'},
    3:  {'name': 'SOLID BREAKABLE NORMAL'},
    4:  {'name': 'SOLID DAMAGE'},
    5:  {'name': 'SEMISOLID'},
    6:  {'name': 'SEMISOLID WEAK'},
    7:  {'name': 'WATER STANDARD'},
    8:  {'name': 'WATER SURFACE'},
    9:  {'name': 'WATER CURRENT', 'extraDataName': 'Strength (0=full force left, 255=full force right)'},
    17: {'name': 'ITEM BLOCK STANDARD', 'extraDataName': 'Content', 'extraDataType': 'objId'},
    18: {'name': 'COIN BLOCK STANDARD'},
    19: {'name': 'COIN BLOCK MULTI', 'extraDataName': 'Coin Count'},
    21: {'name': 'ITEM BLOCK INVISIBLE', 'extraDataName': 'Content', 'extraDataType': 'objId'},
    22: {'name': 'COIN BLOCK INVISIBLE'},
    24: {'name': 'VINE BLOCK'},
    25: {'name': 'ITEM BLOCK INFINITE', 'extraDataName': 'Content', 'extraDataType': 'objId'},
    81: {'name': 'WARP TILE', 'extraDataName': 'Target Warp ID'},
    82: {'name': 'WARP PIPE SLOW', 'extraDataName': 'Target Warp ID'},
    83: {'name': 'WARP PIPE RIGHT SLOW', 'extraDataName': 'Target Warp ID'},
    84: {'name': 'WARP PIPE FAST', 'extraDataName': 'Target Warp ID'},
    85: {'name': 'WARP PIPE RIGHT FAST', 'extraDataName': 'Target Warp ID'},
    86: {'name': 'LEVEL END WARP', 'extraDataName': 'Target Level ID'},
    160:{'name': 'FLAGPOLE', 'extraDataName': 'Coin Award (0=no, 1=yes)'},
    165:{'name': 'VINE'},
    240:{'name': 'VOTE BLOCK'},
};

var objDefs = {
    1:   {'name': 'PLAYER', 'paramDefs': [{'name': 'skin'},{'name': 'isDev'}]},
    17:  {'name': 'GOOMBA', 'paramDefs': [{'name': 'variant'}]},
    18:  {'name': 'KOOPA TROOPA GREEN', 'paramDefs': [{'name': 'fly'}, {'name': 'variant'}]},
    19:  {'name': 'KOOPA TROOPA RED', 'paramDefs': [{'name': 'fly'}, {'name': 'variant'}]},
    21:  {'name': 'FLYING FISH', 'paramDefs': [{'name': 'delay'}, {'name': 'impulse'}]},
    22:  {'name': 'PIRANHA PLANT', 'paramDefs': [{'name': 'variant'}, {'name': 'direction'}]},
    25:  {'name': 'BOWSER', 'paramDefs': [{'name': 'attackType'}]},
    33:  {'name': 'FIRE BAR', 'paramDefs': [{'name': 'phase'}, {'name': 'length'}]},
    34:  {'name': 'LAVA BUBBLE', 'paramDefs': [{'name': 'delay'}, {'name': 'impulse'}]},
    35:  {'name': 'BILL BLASTER', 'paramDefs': [{'name': 'delay'}, {'name': 'direction'}]},
    36:  {'name': 'BULLET', 'paramDefs': [{'name': 'direction'}]},
    37:  {'name': 'OBJECT SPAWNER', 'paramDefs': [{'name': 'objectType'}, {'name': 'delay'}, {'name': 'direction'}]},
    49:  {'name': 'HAMMER BRO', 'paramDefs': [{'name': 'phase'}]},
    81:  {'name': 'MUSHROOM'},
    82:  {'name': 'FIRE FLOWER'},
    83:  {'name': 'ONEUP'},
    84:  {'name': 'STAR'},
    85:  {'name': 'AXE'},
    86:  {'name': 'POISON MUSHROOM'},
    97:  {'name': 'COIN'},
    100: {'name': 'GOLD FLOWER'},
    145: {'name': 'PLATFORM', 'paramDefs': [{'name': 'length'}, {'name': 'offX'}, {'name': 'offY'}, {'name': 'speed'}, {'name': 'loop'}, {'name': 'delay'}, {'name': 'direction'}]},
    146: {'name': 'BUS PLATFORM', 'paramDefs': [{'name': 'length'}, {'name': 'offX'}, {'name': 'offY'}, {'name': 'speed'}]},
    149: {'name': 'SPRING'},
    161: {'name': 'FIREBALL PROJECTILE', 'paramDefs': [{'name': 'dir'},{'name': 'owner'},{'name': 'skin'}]},
    162: {'name': 'FIRE BREATH PROJECTILE'},
    163: {'name': 'HAMMER PROJECTILE', 'paramDefs': [{'name': 'owner'}, {'name': 'delay'}]},
    177: {'name': 'FLAG'},
    253: {'name': 'TEXT', 'paramDefs': [{'name': 'offset'}, {'name': 'size'}, {'name': 'color'}, {'name': 'text'}]},
    254: {'name': 'CHECKMARK'},
};
